Vagrant.configure("2") do |config|
  config.vm.define "lamp"
  config.vm.box = "debian/bookworm64"
  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "lamp"
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.hostname = "lamp"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder "../web", "/var/www/html", owner: "www-data", group: "www-data"

  config.vm.provision "shell", inline: <<-SHELL
sudo apt-get -q=2 update && sudo apt-get -q=2 -y upgrade
sudo DEBIAN_FRONTEND=noninteractive apt-get -q=2 -y install apache2 php libapache2-mod-php php-mysql mariadb-server
sudo apt-get -q=2 autoclean
sudo apt-get -q=2 autoremove

cat > /etc/php/8.2/apache2/conf.d/99-lamp.ini << EOD
upload_max_filesize=512M
post_max_size=512M
memory_limit=512M
EOD

sudo service apache2 restart
sudo service mysql restart

MYSQL_ROOT_PASSWORD="secure"
MYSQL_USER="dbuser"
MYSQL_USER_PASSWORD="dbpassword"
MYSQL_DATABASE="lamp"
mysqladmin -u root password "$MYSQL_ROOT_PASSWORD"
mysql -u root -e "CREATE DATABASE $MYSQL_DATABASE;"
mysql -u root -e "CREATE USER '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_USER_PASSWORD';"
mysql -u root -e "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'localhost';"
mysql -u root -e "FLUSH PRIVILEGES;"
echo "127.0.0.1 db" >> /etc/hosts
  SHELL
end
