version: '3'
name: lamp-task
services:
  db:
    container_name: lamp-task-db
    image: mysql:8.2
    environment:
      - MYSQL_ROOT_PASSWORD=secure
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=lamp

  web:
    container_name: lamp-task-web
    build:
      context: ./
    ports:
      - "8080:80"
    volumes:
      - ./docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini
      - ../web:/var/www/html
    depends_on:
      - db
